export const teamMembersData = [
    {
        firstName: 'Mike',
        lastName: 'Sweet',
        title: 'Founder',
        image: 'https://fidelis-website-storage.s3.us-east-2.amazonaws.com/team-content/headshots/Mike_Sweet_Headshot.png',
        bio: "Mike founded Fidelis in 2002 and has devoted the last 20 years to building and delivering solutions to clients in ERP, plant floor automation, and business intelligence. \n\nBefore starting Fidelis, Mike worked as a Data Architect and Software Consultant for Accenture and other boutique firms.  He wishes he had started Fidelis earlier than he did. \n\nMike graduated from Case Western Reserve University with BS in Industrial Engineering, Magna Cum Laude, with special awards for the top graduate in Industrial Engineering and French.  Mike also earned a Master's of Business Administration from Case. \n\nOutside of work, Mike spends time with his family, plays piano, and is involved with charitable organizations within the Catholic Church.  His most recent involvements are related to homelessness and the Pro Life cause.",
        linkedIn: 'https://www.linkedin.com/in/mike-sweet-071871/',
    },
    {
        firstName: 'Joe',
        lastName: 'Goletz',
        title: 'Director of Consulting',
        image: 'https://fidelis-website-storage.s3.us-east-2.amazonaws.com/team-content/headshots/Joe_Goletz_Headshot.png',
        bio: 'As Director of Consulting, Joe leads over a dozen consultants in delivering data-driven solutions for large-sized enterprises. A results-oriented professional, Joe\'s has an established record in project management, data analysis, software implementation, data quality/data governance as well as operational and financial management. \n\nJoe graduated from John Carroll University with a Bachelors in Accounting and subsequently earned his CPA certification. \n\nIn his free time, Joe enjoys vegetable gardening, hiking, kayaking, baseball, basketball, football, and golf.',
        linkedIn: '',
    },
    {
        firstName: 'Matt',
        lastName: 'Sweet',
        title: 'Data Consulting',
        image: 'https://fidelis-website-storage.s3.us-east-2.amazonaws.com/team-content/headshots/Matt_Sweet_Headshot.png',
        bio: 'Matt joined Fidelis Partners in 2013.\n\nHe is a graduate of the Ohio State University with undergraduate work completed in accounting and masters work in public policy and natural resources.  Matt brings 25+ years of financial services, data architecture, business analysis and risk experience to the team and our clients.   He has supported a breadth of our clients within industries ranging from manufacturing to parts and services distribution to financial services.\n\nOutside of the office, Matt enjoys hiking, backpacking, fishing and kayaking as well as woodworking, cooking and spending time with his family.',
        linkedIn: 'https://www.linkedin.com/in/matt-sweet-6592189/',
    },
    {
        firstName: 'Paul',
        lastName: 'Malhotra',
        title: 'Data Architecture',
        image: 'https://fidelis-website-storage.s3.us-east-2.amazonaws.com/team-content/headshots/Paul_Malhotra_Headshot.png',
        bio: "Paul is an engineering graduate from Case Western Reserve University with 30+ years of industry experience. He has provided data driven solutions for BP Oil, Lubrizol, State Industrial Products, Hodell-Natco Industries, and Garland Industries. Paul is currently engaged in the design and development of a Data Warehouse that provides Business Intelligence solutions for the enterprise encompassing several divisions with varying business models and ERP's. In addition, he continues to remain engaged in providing data analysis and system integration solutions. \n\nIn his free time, Paul enjoys gardening, playing the piano, woodworking, and enjoying our local sites.",
        linkedIn: 'https://www.linkedin.com/in/pkmalhotra/',
    },
    {
        firstName: 'Adam',
        lastName: 'Giese',
        title: 'ERP Systems Engineering',
        image: 'https://fidelis-website-storage.s3.us-east-2.amazonaws.com/team-content/headshots/Adam_Giese_Headshot.png',
        // bio: "Adam has been a versatile resource handling roles of project management, data warehousing, data analysis, web and api development, and custom software solutions for small businesses. Adam spends his free time hiking, biking, and catching the occasional baseball game.",
        bio: "As a Senior ERP Systems Engineer, Adam directly addresses core manufacturing challenges via data warehousing, project management, web and api development, data analysis, and custom software solutions for small businesses. \n\nAdam has degrees in Computer Engineering and Mathematics from the University of Illinois, and has since worked in engineering, consulting, and project management roles for companies ranging from $50M to $50B in size. \n\nAdam spends his free time hiking, biking, and catching the occasional baseball game.",
        linkedIn: '',
    },
    {
        firstName: 'Jamie',
        lastName: 'Knue',
        title: 'Software Engineering, Business Intelligence',
        image: 'https://fidelis-website-storage.s3.us-east-2.amazonaws.com/team-content/headshots/Jamie_Knue_Headshot.png',
        bio: "Jamie is an MBA graduate of Case Western Reserve University's Weatherhead School of Management. He has over 25 years of experience as an ETL architect, data architect, software architect, and project lead, and has led projects in the Financial, Manufacturing, and Higher Education sectors. \n\nJamie has been with Fidelis for over 10 years. In his leisure time Jamie enjoys film, tabletop gaming with his children, and writing compilers for obscure programming languages.",
        linkedIn: 'https://www.linkedin.com/in/jamie-knue-397b082/',
    },
    {
        firstName: 'Tyler',
        lastName: 'Deming',
        title: 'Business Intelligence',
        image: 'https://fidelis-website-storage.s3.us-east-2.amazonaws.com/team-content/headshots/Tyler_Deming_Headshot.png',
        // bio: "Since joining the team in early 2021, Tyler has supported the expansion of Fidelis' client reporting systems and the improvement of delivered BI. This includes working across multiple client platforms and performing thorough consultation and database maintenance. \n\nLocated in Lakewood, Ohio, Tyler enjoys time with his family, catching up with friends and chasing the perfect golf swing.",
        bio: "Tyler acts as a Business Intelligence Analyst, supporting the expansion of client reporting systems and implementing new BI solutions. \n\nTyler graduated from the University of Akron with a Bachelors in Media and has since discovered an affinity for database consultancy and technical solution building for mid-sized manufacturers. \n\nNow retired from his time as a radio host, Tyler enjoys time with his family, catching up with friends and chasing the perfect golf swing.",
        linkedIn: 'https://www.linkedin.com/in/tylerdeming/',
    },
    {
        firstName: 'Patrick',
        lastName: 'Sweet',
        title: 'ERP Systems Engineering',
        // image: defaultProfileIcon,
        image: 'https://fidelis-website-storage.s3.us-east-2.amazonaws.com/team-content/headshots/Patrick_Sweet_Headshot.png',
        bio: "Patrick serves as an ERP System Engineer, committed to enabling new and existing manufacturing clients to integrate and operate on Steel Viking ERP. \n\nPrior to joining Fidelis, Patrick graduated with a B.E. in Computer Science from the University of Notre Dame, with Business and RE minors. Patrick experience in software solutions includes a full stack application used in a dozen locales at Amazon, among others. In college, Patrick started, managed, and scaled a service business, followed by a successful exit.\n\nIn his free time, Patrick enjoys reading, coaching basketball at his local grade school, and building solutions for his most recent enterprising endeavor. ",
        linkedIn: 'https://www.linkedin.com/in/patricksweet3/',
    },
    
]
